name: End-to-end tests
on: [push]
env:
  SITE_URL: "http://localhost:8000"
  METOMIC_CLIENT_ID: ${{ secrets.METOMIC_CLIENT_ID }}
  GHOST_API_URL: http://gatsby.ghost.io
  GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
jobs:
  cypress-run-linux:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test:e2e:ci
