name: Unit testing
on: [push]
jobs:
  jest-run:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Install modules
         run: npm ci
       - name: Run tests
         run: npm test:jest
